<?php
/**
 * Solwin Infotech
 * Solwin Contact Form Widget Extension
 *
 * @category   Solwin
 * @package    Solwin_Contactwidget
 * @copyright  Copyright © 2006-2016 Solwin (https://www.solwininfotech.com)
 * @license    https://www.solwininfotech.com/magento-extension-license/ 
 */
$widgetEnable = $this->getConfigValue('contactwidget_section/general/enable');
$captchaSitekey = $this->getConfigValue('contactwidget_section/recaptcha/recaptcha_sitekey');
$captchaTheme = $this->getConfigValue('contactwidget_section/recaptcha/recaptcha_theme');
$formActionUrl = $this->getFormActionUrl();
$helper = $this->helper('Solwin\Contactwidget\Helper\Data');
$currPageUrl = $helper->getCurrentUrls();
?>
<style>
.benefits-heading {
    font-size: 30px;
    margin-bottom: 35px;
}
.solution-containt {
    font-size: 17px;
}
.container-fluid {
    padding-right: 0px;
    padding-left: 0px;
}
.oppertunitie{
background: #f6f6f6;
padding-top: 55px;
}
.senior {
font-size: 18px;
    font-weight: 700;
    color: #002846;
    margin-bottom: 20px;
margin-top: 30px;
}
.manager-txt {
font-size: 16px;
    color: #000;
    line-height: 25px;
    word-spacing: 2px;
    font-weight: 600;
}
.view-dtl {
    display: table-caption;
    background-color: #00abfa;
    color: #fff !important;
    font-weight: 700;
    border-radius: 5px;
    font-size: 12px;
    padding-top: 10px;
    padding-bottom: 8px;
    width: 115px;
}
.aply-now {
    display: table-caption;
    background-color: #f6f6f6;
    color: #00abfa;
    font-weight: 700;
     border-radius: 5px;
    font-size: 12px;
    padding-top: 10px;
    padding-bottom: 8px;
    width: 115px;
    margin-top: 10px;
    border: 1px solid #00abfa;
}
.aply-now:hover {
    color: #00abfa;
}
.project-butn {
float:right;
    margin-top: 70px;
}
.bod-09 {
    border-bottom: 1px solid #3c3c3c80;
    margin-top: 29px;
    margin-bottom: 16px;
}
@media (min-width: 768px){
.page-header.type16 .navigation {
    padding: 0 0px;
}
}
.form-input-setting{
    text-align: left;
    font-size: 15px;
    font-weight: 600;
    color: #2D2D2D;
        }
.upload-btn-wrapper {
  position: relative;
  overflow: hidden;
  display: block;
    margin-top: 10px;
}
.up-btn{
    height: 50px !important;
    width: 100% !important;
    color: #00abfa !important;
    border-radius: 0px !important;
    border: 1px solid #00abfa !important;
}
.btn {
  border: 2px solid gray;
  color: gray;
  background-color: white;
  padding: 8px 20px;
  border-radius: 8px;
  font-size: 20px;
  font-weight: bold;
}

.upload-btn-wrapper input[type=file] {
  font-size: 100px;
  position: absolute;
  left: 0;
  top: 0;
  opacity: 0;
}
.main_fill_head{
    margin-bottom: 0px !important;
    font-size: 41px !important;
   }
.oppertunitie p{
    color: #000;
    font-weight: 600;
    font-size: 16px;
    text-align: center;
    margin: 0px;
       }
#succ{
     margin-top: 20px;
    background: #0CC485;
    padding: 10px;
    color: #fff;
    font-weight: bold;
     display:none;
       }
.bg_home_benifit .container{
       padding-bottom: 0px !important;
           }
.career_para_set{
    width: 400px;
    float: left;
        }
.career_para_dis{
        float: right;
       }
</style>
<?php if($widgetEnable){?>
<div class="career_main"  style="    margin-bottom: 40px;">
    <section class="oppertunitie">
        <div class="container"> 
            <h2 class="benefits-heading">APPLY TO <span> MEDICOS</span></h2>
            <p> If you are interested in joining a growing team, please submit your resume today! </p>
        <form class="form contact" action="<?php echo $formActionUrl;?>" id="contact-form" method="post" enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
            <div class="container" style="padding-top: 50px;padding-bottom: 70px;">
                <div class="row">
                    <!--<fieldset class="fieldset">-->
                <!--<legend class="legend"><span><?php /* @escapeNotVerified */ echo $this->getData('cc_title') ?></span></legend><br />-->
                <!--<div class="field note no-label"><?php /* @escapeNotVerified */ echo $this->getData('cc_content') ?></div>-->
                <div class="col-md-6 col-sm-12 text-left">
                    <div class="form-group text-left form-input-setting">
                    <div class="field name required">
                        <label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('Name*') ?></span></label>
                        <div class="control" style=" margin-top: 10px;margin-bottom: 40px;">
                            <input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" class="input-text form-control" type="text" data-validate="{required:true}" style="height: 50px;"/>
                        </div>
                    </div>
                    </div>
                    <?php
                    if ($this->getData('cc_enable_phoneno')) {
                        ?>
                    <div class="form-group text-left form-input-setting">
                    <div class="field telephone">
                        <label class="label" for="telephone"><span><?php /* @escapeNotVerified */ echo __('Phone*') ?></span></label>
                        <div class="control" style=" margin-top: 10px;margin-bottom: 40px;">
                            <input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Phone') ?>" value="" class="input-text form-control" type="text" style="height: 50px;"/>
                        </div>
                    </div>
                    </div>
                    <?php } ?>
                    <div class="form-group text-left form-input-setting">
                    <div class="field name required">
                        <label class="label" for="subject"><span><?php /* @escapeNotVerified */ echo __('Position Applied*') ?></span></label>
                        <div class="control" style=" margin-top: 10px;margin-bottom: 40px;">
                            <input name="subject" id="subject" title="<?php /* @escapeNotVerified */ echo __('Position Applied') ?>" class="input-text form-control" type="text" data-validate="{required:true}" style="height: 50px;"/>
                        </div>
                    </div>
                    </div>
                </div>
                <div class="col-md-6 col-sm-12 text-left form-input-setting">
                    <div class="form-group text-left form-input-setting">
                    <div class="field comment required">
                        <label class="label" for="comment"><span><?php /* @escapeNotVerified */ echo __('Address*') ?></span></label>
                        <div class="control" style=" margin-top: 10px;margin-bottom: 40px;">
                            <input name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('Address') ?>" class="input-text form-control" type="text" data-validate="{required:true}" style="height: 50px;"/>
                        </div>
                    </div>
                    </div>
                    <div class="form-group text-left form-input-setting">
                    <div class="field email required">
                        <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email*') ?></span></label>
                        <div class="control" style=" margin-top: 10px;margin-bottom: 40px;">
                            <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="input-text form-control" type="email" data-validate="{required:true, 'validate-email':true}" style="height: 50px;"/>
                        </div>
                    </div>
                    </div>
                    <script type="text/javascript">
                    	jQuery(document).ready(function($){
                    		$('#myfile').change(function(e){
                    		  $('.choosefile').text('');
							  $in=$(this);
							  var text = $in.val();
							  var text = text.substring(text.lastIndexOf("\\") + 1, text.length);
							  $('.choosefile').text( text);
							});
                    	})
                    </script>
                    <div class="form-group text-left form-input-setting">
                        <label for="email">Upload Your Resume*<small>(Only PDF file allowed)</small> &nbsp;&nbsp;&nbsp; <small class="choosefile"></small></label>
                        <div class="upload-btn-wrapper">
                            <button class="btn up-btn">Upload Your Resume</button>
                            <input type="file" name="myfile" id="myfile" />
                        </div>
                    </div>
                </div>
                
                
                 <?php
                    if ($this->getData('cc_enable_recaptcha')) {
                        ?>
                <div class="field comment required">
                    <label class="label" for="captcha"><span><?php /* @escapeNotVerified */ echo __('ReCaptcha') ?></span></label>
                    <div class="control">
                        <script src="https://www.google.com/recaptcha/api.js"></script>
                        <div class="g-recaptcha" data-sitekey="<?php echo $captchaSitekey;?>" data-theme="<?php echo $captchaTheme; ?>"></div>
                    </div>
                </div>       
                <?php } ?> 
            <!--</fieldset>-->
                <div class="col-md-12">
                    <div class="primary text-center">
                        <input type="hidden" name="currUrl" id="currUrl" value="<?php echo $currPageUrl; ?>" />
                        <input type="hidden" name="enablerecaptcha" id="currUrl" value="<?php echo $this->getData('cc_enable_recaptcha'); ?>" />
                        <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary" style="margin: 0px auto;margin-top: 30px;background: #00abfa;color: #fff;border-radius: 7px;font-size: 13px;padding: 0px;height: auto;width: 120px;line-height: 37px;text-transform: uppercase;border:0px;">
                            <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
                        </button>
                    </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</section>
</div>
<?php 
}
?>



